const USER_CONNECTED = 'USER_CONNECTED';
const LOGOUT = 'LOGOUT';
const USER_DISCONNECTED = 'USER_DISCONNECTED';
const VERIFY_USER = 'VERIFY_USER';
const MESSAGE_SENT = 'MESSAGE_SENT';
const TYPING = 'TYPING';
const COMMUNITY_CHAT = 'COMMUNITY_CHAT';
const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';

module.exports = {
  USER_CONNECTED,
  LOGOUT,
  VERIFY_USER,
  MESSAGE_SENT,
  TYPING,
  COMMUNITY_CHAT,
  MESSAGE_RECIEVED,
  USER_DISCONNECTED
}